CREATE TABLE "ADVENTURE_TRIP" (
	"TRIP_ID"	DECIMAL(3) NOT NULL,
	"TRIP_NAME"	CHAR(73),
	"START_LOCATION"	CHAR(50),
	"STATE"	CHAR(2),
	"DISTANCE"	NUMBER(4),
	"MAX_GRP_SIZE"	NUMBER(4),
	"TYPE"	CHAR(20),
	"SEASON"	CHAR(20),
	PRIMARY KEY("TRIP_ID")
);